Another Camera fixed
Fixing Error " Assets\CameraManager.cs(43,47): error CS1061: 'InputManager' does not contain a definition for 'cameraInputX' and no accessible extension method 'cameraInputX' accepting a first argument of type 'InputManager' could be found (are you missing a using directive or an assembly reference?) "